# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineFlix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'Locksmith'
  pod "youtube-ios-player-helper"
  pod 'lottie-ios'

end
